movies_list: 'fiveclone_dataset_list.txt'

min_tracklength_segmentation: 10
min_cellsize_segmentation: 3000

spotdiameter: 7
spotdetection_threshold: 2800
spotfilter_size_min: 1.2
spotfilter_size_max: 1.65
spotfilter_mass: 30000

min_burstlength: 2